2019-03-08 11:23:53,813 ERROR 21140 nodejs.ClusterClientNoResponseError: client no response in 10799879ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\web\egg-exam\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
name: "ClusterClientNoResponseError"
pid: 21140
hostname: LAPTOP-QLQ71POJ

2019-03-08 13:43:51,659 ERROR 21140 nodejs.ClusterClientNoResponseError: client no response in 8396747ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\web\egg-exam\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
name: "ClusterClientNoResponseError"
pid: 21140
hostname: LAPTOP-QLQ71POJ

2019-03-08 13:52:58,276 ERROR 18788 nodejs.TypeError: Cannot read property 'length' of undefined
    at exports.getQuestions (D:\web\egg-exam\app\sql\exam.js:54:22)
    at ExamService.getExam (D:\web\egg-exam\app\service\exam\exam.js:121:52)
    at process._tickCallback (internal/process/next_tick.js:178:7)

pid: 18788
hostname: LAPTOP-QLQ71POJ

2019-03-08 13:54:11,896 ERROR 21140 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onread (net.js:659:25)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 21140
hostname: LAPTOP-QLQ71POJ

2019-03-08 13:54:29,739 ERROR 21140 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onread (net.js:659:25)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 21140
hostname: LAPTOP-QLQ71POJ

2019-03-08 13:54:39,499 ERROR 19828 nodejs.TypeError: Cannot read property 'indexOf' of undefined
    at exports.getQuestions (D:\web\egg-exam\app\sql\exam.js:54:22)
    at ExamService.getExam (D:\web\egg-exam\app\service\exam\exam.js:121:52)
    at process._tickCallback (internal/process/next_tick.js:178:7)

pid: 19828
hostname: LAPTOP-QLQ71POJ

2019-03-08 13:55:49,602 ERROR 19976 nodejs.ReferenceError: questions_ids is not defined
    at exports.getQuestions (D:\web\egg-exam\app\sql\exam.js:55:69)
    at ExamService.getExam (D:\web\egg-exam\app\service\exam\exam.js:122:52)
    at process._tickCallback (internal/process/next_tick.js:178:7)

pid: 19976
hostname: LAPTOP-QLQ71POJ

2019-03-08 13:57:15,033 ERROR 19480 nodejs.ReferenceError: questions_ids is not defined
    at exports.getQuestions (D:\web\egg-exam\app\sql\exam.js:55:69)
    at ExamService.getExam (D:\web\egg-exam\app\service\exam\exam.js:122:52)
    at process._tickCallback (internal/process/next_tick.js:178:7)

pid: 19480
hostname: LAPTOP-QLQ71POJ

2019-03-08 13:58:00,588 ERROR 16608 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'questions.question_id' in 'where clause'
    at Query.Sequence._packetToError (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\Pool.js:199:23)
    at D:\web\egg-exam\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\web\egg-exam\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (D:\web\egg-exam\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (D:\web\egg-exam\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (D:\web\egg-exam\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\web\egg-exam\node_modules\_co@4.6.0@co\index.js:65:19)
    at D:\web\egg-exam\node_modules\_co@4.6.0@co\index.js:54:5
    sql: 
 SELECT
 questions.title AS title,
 questions.questions_id AS questions_id,
 questions.json_path AS json_path,
 subject.subject_text AS subject_text,
 subject.subject_id AS subject_id,
 exam_type.exam_id AS exam_id,
 exam_type.exam_name AS exam_name,
 user.user_name AS user_name,
 user.user_id AS user_id,
 questions_types.questions_type_text as questions_type_text,
 questions_types.questions_type_id as questions_type_id
FROM
 questions,
 questions_types,
 user,
 subject,
 exam_type
WHERE
 questions.user_id=user.user_id
 And 
 questions.subject_id=subject.subject_id
 AND
 questions.exam_id=exam_type.exam_id
 AND
 questions.questions_type_id=questions_types.questions_type_id
 AND questions.question_id in ('msqy4g-icp0zt-nrwi6q-ypmct,65vst-tqms-h5kg6-rfabwg,83nd9t-3126tf-zoa4o9-n1l4pr,krkyz9-lmbb1f-yxn2e-t5q8a,yw91la-o5xtg-m98u9-1y0y7')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'questions.question_id' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "\n SELECT\n questions.title AS title,\n questions.questions_id AS questions_id,\n questions.json_path AS json_path,\n subject.subject_text AS subject_text,\n subject.subject_id AS subject_id,\n exam_type.exam_id AS exam_id,\n exam_type.exam_name AS exam_name,\n user.user_name AS user_name,\n user.user_id AS user_id,\n questions_types.questions_type_text as questions_type_text,\n questions_types.questions_type_id as questions_type_id\nFROM\n questions,\n questions_types,\n user,\n subject,\n exam_type\nWHERE\n questions.user_id=user.user_id\n And \n questions.subject_id=subject.subject_id\n AND\n questions.exam_id=exam_type.exam_id\n AND\n questions.questions_type_id=questions_types.questions_type_id\n AND questions.question_id in ('msqy4g-icp0zt-nrwi6q-ypmct,65vst-tqms-h5kg6-rfabwg,83nd9t-3126tf-zoa4o9-n1l4pr,krkyz9-lmbb1f-yxn2e-t5q8a,yw91la-o5xtg-m98u9-1y0y7')"
name: "unhandledRejectionError"
pid: 16608
hostname: LAPTOP-QLQ71POJ

2019-03-08 14:06:36,433 ERROR 15200 nodejs.unhandledRejectionError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'msqy4g-icp0zt-nrwi6q-ypmct','65vst-tqms-h5kg6-rfabwg','83nd9t-3126tf-zoa4o9-n1l4' at line 19
    at Query.Sequence._packetToError (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\Pool.js:199:23)
    at D:\web\egg-exam\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\web\egg-exam\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (D:\web\egg-exam\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (D:\web\egg-exam\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (D:\web\egg-exam\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\web\egg-exam\node_modules\_co@4.6.0@co\index.js:65:19)
    at D:\web\egg-exam\node_modules\_co@4.6.0@co\index.js:54:5
    sql: 
 SELECT
 questions.title AS title,
 questions.questions_id AS questions_id,
 questions.json_path AS json_path,
 subject.subject_text AS subject_text,
 subject.subject_id AS subject_id,
 exam_type.exam_id AS exam_id,
 exam_type.exam_name AS exam_name,
 user.user_name AS user_name,
 user.user_id AS user_id,
 questions_types.questions_type_text as questions_type_text,
 questions_types.questions_type_id as questions_type_id
FROM
 questions,
 questions_types,
 user,
 subject,
 exam_type
WHERE
 questions.user_id=user.user_id
 And 
 questions.subject_id=subject.subject_id
 AND
 questions.exam_id=exam_type.exam_id
 AND
 questions.questions_type_id=questions_types.questions_type_id
 AND questions.questions_id in (''msqy4g-icp0zt-nrwi6q-ypmct','65vst-tqms-h5kg6-rfabwg','83nd9t-3126tf-zoa4o9-n1l4pr','krkyz9-lmbb1f-yxn2e-t5q8a','yw91la-o5xtg-m98u9-1y0y7'')
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'msqy4g-icp0zt-nrwi6q-ypmct','65vst-tqms-h5kg6-rfabwg','83nd9t-3126tf-zoa4o9-n1l4' at line 19"
sqlState: "42000"
index: 0
sql: "\n SELECT\n questions.title AS title,\n questions.questions_id AS questions_id,\n questions.json_path AS json_path,\n subject.subject_text AS subject_text,\n subject.subject_id AS subject_id,\n exam_type.exam_id AS exam_id,\n exam_type.exam_name AS exam_name,\n user.user_name AS user_name,\n user.user_id AS user_id,\n questions_types.questions_type_text as questions_type_text,\n questions_types.questions_type_id as questions_type_id\nFROM\n questions,\n questions_types,\n user,\n subject,\n exam_type\nWHERE\n questions.user_id=user.user_id\n And \n questions.subject_id=subject.subject_id\n AND\n questions.exam_id=exam_type.exam_id\n AND\n questions.questions_type_id=questions_types.questions_type_id\n AND questions.questions_id in (''msqy4g-icp0zt-nrwi6q-ypmct','65vst-tqms-h5kg6-rfabwg','83nd9t-3126tf-zoa4o9-n1l4pr','krkyz9-lmbb1f-yxn2e-t5q8a','yw91la-o5xtg-m98u9-1y0y7'')"
name: "unhandledRejectionError"
pid: 15200
hostname: LAPTOP-QLQ71POJ

2019-03-08 14:09:19,071 ERROR 18212 nodejs.ReferenceError: questions is not defined
    at ExamService.getExam (D:\web\egg-exam\app\service\exam\exam.js:125:28)
    at process._tickCallback (internal/process/next_tick.js:178:7)

pid: 18212
hostname: LAPTOP-QLQ71POJ

2019-03-08 14:09:20,258 ERROR 18212 nodejs.ReferenceError: questions is not defined
    at ExamService.getExam (D:\web\egg-exam\app\service\exam\exam.js:125:28)
    at process._tickCallback (internal/process/next_tick.js:178:7)

pid: 18212
hostname: LAPTOP-QLQ71POJ

2019-03-08 14:09:38,066 ERROR 16536 [-/127.0.0.1/-/12ms GET /exam/exam/w5tcy-g2dts] nodejs.ReferenceError: questions is not defined
    at ExamService.getExam (D:\web\egg-exam\app\service\exam\exam.js:125:28)
    at process._tickCallback (internal/process/next_tick.js:178:7)

pid: 16536
hostname: LAPTOP-QLQ71POJ

2019-03-08 14:09:54,144 ERROR 21140 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onread (net.js:659:25)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 21140
hostname: LAPTOP-QLQ71POJ

2019-03-08 14:09:58,553 ERROR 4984 [-/127.0.0.1/-/10ms GET /exam/exam/w5tcy-g2dts] nodejs.ReferenceError: questions is not defined
    at ExamService.getExam (D:\web\egg-exam\app\service\exam\exam.js:125:28)
    at process._tickCallback (internal/process/next_tick.js:178:7)

pid: 4984
hostname: LAPTOP-QLQ71POJ

2019-03-08 14:13:00,358 ERROR 21140 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onread (net.js:659:25)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 21140
hostname: LAPTOP-QLQ71POJ

2019-03-08 14:28:11,401 ERROR 7504 [-/127.0.0.1/-/12ms GET /exam/exam] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column '0' in 'where clause'
    at Query.Sequence._packetToError (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (D:\web\egg-exam\node_modules\_mysql@2.16.0@mysql\lib\Pool.js:199:23)
    at D:\web\egg-exam\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\web\egg-exam\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (D:\web\egg-exam\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (D:\web\egg-exam\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (D:\web\egg-exam\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\web\egg-exam\node_modules\_co@4.6.0@co\index.js:65:19)
    at D:\web\egg-exam\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `exam_exam` WHERE `0` = 's' AND `1` = 't' AND `2` = 'a' AND `3` = 't' AND `4` = 'u' AND `5` = 's' AND `6` = '>' AND `7` = '-' AND `8` = '1'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '0' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `exam_exam` WHERE `0` = 's' AND `1` = 't' AND `2` = 'a' AND `3` = 't' AND `4` = 'u' AND `5` = 's' AND `6` = '>' AND `7` = '-' AND `8` = '1'"
name: "ER_BAD_FIELD_ERRORError"
pid: 7504
hostname: LAPTOP-QLQ71POJ

2019-03-08 14:32:39,647 ERROR 21256 [-/127.0.0.1/-/26ms DELETE /exam/exam/vucdmp-6n8n] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (D:\web\egg-exam\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (D:\web\egg-exam\node_modules\_co@4.6.0@co\index.js:65:19)
    at D:\web\egg-exam\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (D:\web\egg-exam\node_modules\_co@4.6.0@co\index.js:50:10)
    at RDSClient.createPromise [as update] (D:\web\egg-exam\node_modules\_co@4.6.0@co\index.js:30:15)
    at ExamService.deleteExam (D:\web\egg-exam\app\service\exam\exam.js:121:43)
    at ExamController.destroy (D:\web\egg-exam\app\controller\exam\exam.js:40:49)
    at Object.callFn (D:\web\egg-exam\node_modules\_egg-core@4.14.1@egg-core\lib\utils\index.js:44:21)

pid: 21256
hostname: LAPTOP-QLQ71POJ

2019-03-08 18:56:23,691 ERROR 21140 nodejs.ClusterClientNoResponseError: client no response in 10817544ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\web\egg-exam\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
name: "ClusterClientNoResponseError"
pid: 21140
hostname: LAPTOP-QLQ71POJ

2019-03-11 08:43:52,872 ERROR 21140 nodejs.ClusterClientNoResponseError: client no response in 222444873ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\web\egg-exam\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
name: "ClusterClientNoResponseError"
pid: 21140
hostname: LAPTOP-QLQ71POJ

